# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
        postgres_db:
          image: postgres
          env:
            POSTGRES_USER: postgres
            POSTGRES_HOSTNAME: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Using source
        run: |
          source <(echo ${{ secrets.TEST_ENV }} | base64 --decode)
          echo ${{ secrets.TEST_SECRET }} | base64 --decode 
            > test_file.json
          cat $TEST_SECRET
          echo $POSTGRES_USER

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ secrets.DICTIONARY_WITH_MULTIPLE_LINES }} | base64 --decode > test_file.json
          echo $TEST_VAR
          echo $POSTGRES_USER
        env:
          TEST_VAR: "test_file.json"
          POSTGRES_USER: postgres
